[package]
name = "eq-balances-rpc"
version = "0.1.0"
authors = ["equilibrium"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.42" }
sp-rpc = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.42" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.42" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.42" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.42" }

eq-balances-rpc-runtime-api = { version = "0.1.0", default-features = false, path = "runtime-api", package="eq-balances-rpc-runtime-api" }


[features]
default = ["std"]
std = [
    "eq-balances-rpc-runtime-api/std",
]
