
//! Autogenerated weights for `eq_whitelists`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-17, STEPS: `10`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ivan-GP76`, CPU: `11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/eq-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_whitelists
// --extrinsic=*
// --steps
// 10
// --repeat
// 5
// --output
// ./runtime/equilibrium/src/weights/pallet_whitelists.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight}};
use sp_std::marker::PhantomData;

/// Weight functions for `eq_whitelists`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_whitelists::WeightInfo for WeightInfo<T> {
	// Storage: Whitelists WhiteList (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqRate NowMillisOffset (r:1 w:0)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	fn add_to_whitelist() -> Weight {
		Weight::from_ref_time(38_377_000 as u64)
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Whitelists WhiteList (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: Oracle PricePoints (r:17 w:17)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	fn remove_from_whitelist() -> Weight {
		Weight::from_ref_time(107_088_000 as u64)
			.saturating_add(T::DbWeight::get().reads(20 as u64))
			.saturating_add(T::DbWeight::get().writes(20 as u64))
	}
}
