
//! Autogenerated weights for `eq_dex`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-01-09, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `muctep-osx-m1.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/eq-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_dex
// --extrinsic=*
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/equilibrium/src/weights/pallet_dex.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight}};
use sp_std::marker::PhantomData;

/// Weight functions for `eq_dex`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_dex::WeightInfo for WeightInfo<T> {
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:0)
	// Storage: EqDex BestPriceByAsset (r:1 w:1)
	// Storage: EqDex ChunkCorridorByAsset (r:1 w:0)
	// Storage: Oracle PricePoints (r:2 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:1)
	// Storage: EqMarginCall MaintenanceTimers (r:1 w:0)
	// Storage: EqDex OrderIdCounter (r:1 w:1)
	// Storage: EqDex OrdersByAssetAndChunkKey (r:1 w:1)
	// Storage: EqDex ActualChunksByAsset (r:1 w:1)
	fn create_limit_order() -> Weight {
		Weight::from_ref_time(108_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(13 as u64))
			.saturating_add(T::DbWeight::get().writes(5 as u64))
	}
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:0)
	// Storage: EqDex BestPriceByAsset (r:1 w:1)
	// Storage: EqDex ChunkCorridorByAsset (r:1 w:0)
	// Storage: Oracle PricePoints (r:2 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:1 w:0)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:1)
	// Storage: EqMarginCall MaintenanceTimers (r:1 w:0)
	// Storage: EqDex OrderIdCounter (r:1 w:1)
	// Storage: EqDex OrdersByAssetAndChunkKey (r:1 w:1)
	// Storage: EqDex ActualChunksByAsset (r:1 w:1)
	fn create_market_order() -> Weight {
		Weight::from_ref_time(105_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(13 as u64))
			.saturating_add(T::DbWeight::get().writes(5 as u64))
	}
	// Storage: System Account (r:2 w:2)
	// Storage: Oracle PricePoints (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:0)
	// Storage: EqAggregates AccountUserGroups (r:6 w:2)
	// Storage: EqAggregates TotalUserGroups (r:1 w:1)
	// Storage: EqDex OrdersByAssetAndChunkKey (r:1 w:1)
	// Storage: EqDex BestPriceByAsset (r:1 w:0)
	// Storage: EqDex ActualChunksByAsset (r:1 w:1)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:1)
	fn delete_order() -> Weight {
		Weight::from_ref_time(158_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(19 as u64))
			.saturating_add(T::DbWeight::get().writes(8 as u64))
	}
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqDex OrdersByAssetAndChunkKey (r:1 w:1)
	// Storage: Subaccounts OwnerAccount (r:1 w:0)
	// Storage: EqDex BestPriceByAsset (r:1 w:0)
	// Storage: EqDex ActualChunksByAsset (r:1 w:1)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:1)
	fn delete_order_external() -> Weight {
		Weight::from_ref_time(53_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(6 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: EqDex ChunkCorridorByAsset (r:1 w:1)
	fn update_asset_corridor() -> Weight {
		Weight::from_ref_time(9_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: EqRate Keys (r:1 w:0)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqDex OrdersByAssetAndChunkKey (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Oracle PricePoints (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:0)
	// Storage: EqAggregates AccountUserGroups (r:6 w:2)
	// Storage: EqAggregates TotalUserGroups (r:1 w:1)
	// Storage: EqDex BestPriceByAsset (r:1 w:0)
	// Storage: EqDex ActualChunksByAsset (r:1 w:1)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:1)
	fn validate_unsigned() -> Weight {
		Weight::from_ref_time(207_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(20 as u64))
			.saturating_add(T::DbWeight::get().writes(8 as u64))
	}
}
