
//! Autogenerated weights for `eq_oracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-17, STEPS: `10`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ivan-GP76`, CPU: `11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/eq-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_oracle
// --extrinsic=*
// --steps
// 10
// --repeat
// 5
// --output
// ./runtime/equilibrium/src/weights/pallet_oracle.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight}};
use sp_std::marker::PhantomData;

/// Weight functions for `eq_oracle`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_oracle::WeightInfo for WeightInfo<T> {
	// Storage: Whitelists WhiteList (r:1 w:0)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: Oracle PricePoints (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqRate NowMillisOffset (r:1 w:0)
	// Storage: FinancialModule Updates (r:1 w:1)
	// Storage: FinancialModule PriceLogs (r:1 w:0)
	/// The range of component `b` is `[1, 20]`.
	fn set_price(b: u32, ) -> Weight {
		Weight::from_ref_time(64_999_000 as u64)
			// Standard Error: 53_000
			.saturating_add(Weight::from_ref_time(341_000 as u64).saturating_mul(b as u64))
			.saturating_add(T::DbWeight::get().reads(7 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
}
