//! Autogenerated weights for eq_liquidity_farming
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-06-18, STEPS: [10, ], REPEAT: 5, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/eq-node
// benchmark
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_liquidity_farming
// --extrinsic
// *
// --raw
// --steps
// 10
// --repeat
// 5
// --output
// ./runtime/equilibrium/src/weights/pallet_liquidity_farming.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for eq_liquidity_farming.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_liquidity_farming::WeightInfo for WeightInfo<T> {
    fn set_auto_reward_enabled() -> Weight {
        (Weight::from_parts(3_000_000, 0)).saturating_add(T::DbWeight::get().writes(1))
    }
    fn reward() -> Weight {
        (Weight::from_parts(285_900_000, 0))
            .saturating_add(T::DbWeight::get().reads(22))
            .saturating_add(T::DbWeight::get().writes(7))
    }
    fn reward_external() -> Weight {
        (Weight::from_parts(323_300_000, 0))
            .saturating_add(T::DbWeight::get().reads(24))
            .saturating_add(T::DbWeight::get().writes(7))
    }
    fn validate_unsigned() -> Weight {
        (Weight::from_parts(411_000_000, 0))
            .saturating_add(T::DbWeight::get().reads(26))
            .saturating_add(T::DbWeight::get().writes(7))
    }
}
