//! Autogenerated weights for eq_curve_distribution
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-07-01, STEPS: [10, ], REPEAT: 5, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/eq-node
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=eq_curve_distribution
// --extrinsic=*
// --raw
// --steps=10
// --repeat=5
// --output=./runtime/equilibrium/src/weights/pallet_curve_distribution.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for eq_curve_distribution.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_curve_distribution::WeightInfo for WeightInfo<T> {
    fn distribute() -> Weight {
        (Weight::from_ref_time(972_217_000))
            .saturating_add(T::DbWeight::get().reads(28))
            .saturating_add(T::DbWeight::get().writes(9))
    }
}
