
//! Autogenerated weights for `eq_balances`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-17, STEPS: `10`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ivan-GP76`, CPU: `11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/eq-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_balances
// --extrinsic=*
// --steps
// 10
// --repeat
// 5
// --output
// ./runtime/equilibrium/src/weights/pallet_balances.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight}};
use sp_std::marker::PhantomData;

/// Weight functions for `eq_balances`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_balances::WeightInfo for WeightInfo<T> {
	// Storage: EqBalances IsTransfersEnabled (r:0 w:1)
	fn enable_transfers() -> Weight {
		Weight::from_parts(6_531_000 as u64, 0)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:0 w:1)
	fn disable_transfers() -> Weight {
		Weight::from_parts(6_116_000 as u64, 0)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts OwnerAccount (r:3 w:0)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: Oracle PricePoints (r:2 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqRate NowMillisOffset (r:1 w:0)
	// Storage: EqBalances Account (r:3 w:0)
	// Storage: EqAggregates AccountUserGroups (r:9 w:2)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	fn transfer() -> Weight {
		Weight::from_parts(351_659_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(25 as u64))
			.saturating_add(T::DbWeight::get().writes(7 as u64))
	}
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqRate NowMillisOffset (r:1 w:0)
	// Storage: EqBalances XcmNativeTransfers (r:1 w:1)
	/// The range of component `z` is `[1, 100]`.
	fn allow_xcm_transfers_native_for(z: u32, ) -> Weight {
		Weight::from_parts(17_313_000 as u64, 0)
			// Standard Error: 31_000
			.saturating_add(Weight::from_parts(2_809_000 as u64, 0).saturating_mul(z as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(z as u64)))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(z as u64)))
	}
	// Storage: EqBalances XcmNativeTransfers (r:0 w:1)
	/// The range of component `z` is `[1, 100]`.
	fn forbid_xcm_transfers_native_for(z: u32, ) -> Weight {
		Weight::from_parts(5_769_000 as u64, 0)
			// Standard Error: 5_000
			.saturating_add(Weight::from_parts(1_345_000 as u64, 0).saturating_mul(z as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(z as u64)))
	}
	// Storage: EqBalances DailyXcmLimit (r:0 w:1)
	fn update_xcm_transfer_native_limit() -> Weight {
		Weight::from_parts(6_026_000 as u64, 0)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: EqBalances IsXcmTransfersEnabled (r:1 w:0)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: EqAggregates AccountUserGroups (r:3 w:0)
	// Storage: EqAggregates TotalUserGroups (r:1 w:1)
	// Storage: ParachainSystem HostConfiguration (r:1 w:0)
	// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
	fn xcm_transfer_native() -> Weight {
		Weight::from_parts(93_690_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(9 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: EqBalances IsXcmTransfersEnabled (r:1 w:0)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: ParachainInfo ParachainId (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: EqAggregates AccountUserGroups (r:3 w:0)
	// Storage: EqAggregates TotalUserGroups (r:1 w:1)
	fn xcm_transfer() -> Weight {
		Weight::from_parts(96_984_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(8 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}

	fn on_initialize(_: u32) -> Weight {
		todo!()
	}
}
