[package]
authors = ["equilibrium"]
edition = "2018"
name = "common-runtime"
version = "3.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}
xcm = { workspace = true }
frame-support = {workspace = true}
substrate-fixed = { workspace = true, features = ["serde"] }
sp-core = { workspace = true }
equilibrium-curve-amm = { workspace = true }
financial-pallet = { workspace = true }
financial-primitives = { workspace = true }
eq-primitives = { path = "../../eq-primitives", default-features = false }
eq-utils = { path = "../../eq-utils", default-features = false }

[dependencies.codec]
package = "parity-scale-codec"
version = "3.0.0"
default-features = false
features = ["derive", "max-encoded-len"]

[features]

default = ["std"]
std = [
    "codec/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-core/std",
    "frame-support/std",
    "substrate-fixed/std",
    "xcm/std",
    "eq-primitives/std",
    "eq-utils/std",
    "equilibrium-curve-amm/std",
    "financial-pallet/std",
    "financial-primitives/std",
]
production = [
    "eq-primitives/production",
]
