[package]
name = "eq-xdot-pool-rpc"
version = "0.1.0"
authors = ["equilibrium"]
edition = "2018"

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.1.0" }
sp-rpc = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.1.0" }
sp-api = { workspace = true }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.1.0" }
substrate-fixed = { workspace = true, features = ["serde"] }

eq-xdot-pool-rpc-runtime-api = { version = "0.1.0", default-features = false, path = "runtime-api", package="eq-xdot-pool-rpc-runtime-api" }


[features]
default = ["std"]
std = [
    "eq-xdot-pool-rpc-runtime-api/std",
    "substrate-fixed/std"
]
