[package]
name = "eq-wrapped-dot"
version = "0.1.0"
authors = ["equilibrium"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}

# third-party dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.123", optional = true }

sp-core = { workspace = true }
sp-io = { workspace = true }
sp-staking = { workspace = true }
pallet-staking = { workspace = true }
substrate-fixed = { workspace = true, features = ["serde"] }
frame-support = { workspace = true }
eq-primitives = { path = "../../eq-primitives", default-features = false }
eq-utils = { path = "../../eq-utils", default-features = false }
eq-whitelists = { path = "../eq-whitelists", default-features = false, optional = true }
eq-assets = { path = "../eq-assets", default-features = false }
eq-oracle = { path = "../eq-oracle", default-features = false, optional = true }
eq-xcm = { path = "../../eq-xcm", default-features = false }
xcm = { workspace = true }

[dev-dependencies.eq-balances]
package = "eq-balances"
path = "../eq-balances"
version = "0.1.0"

[dev-dependencies.eq-aggregates]
package = "eq-aggregates"
path = "../eq-aggregates"
version = "0.1.0"

[dev-dependencies.test-utils]
default-features = false
package = "test-utils"
path = "../../test-utils"
version = "0.1.0"

[dev-dependencies.xcm-builder]
default-features = false
git = "https://github.com/paritytech/polkadot-sdk"
branch = "release-polkadot-v1.1.0"
package = "staging-xcm-builder"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"eq-primitives/std",
	"eq-utils/std",
	"substrate-fixed/std",
	"xcm/std",
	"eq-xcm/std",
	"sp-staking/std",
	"pallet-staking/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
  "eq-whitelists",
  "eq-oracle",
  "eq-assets/runtime-benchmarks",
]
try-runtime = [
  "frame-support/try-runtime",
]
