[package]
authors = ["equilibrium"]
edition = "2018"
name = "eq-node-runtime"
version = "3.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}
sp-io = { workspace = true }
sp-core = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-session = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
hex-literal = { version = "0.3.1", optional = false }
serde = {version = "1.0.123", features = ["derive"], optional = true}
serde_json = {git = "https://github.com/nikvolf/json", default-features = false, features = ["alloc"]}
static_assertions = "1.1.0"
smallvec = "1.6.1"
log = { version = "0.4.17", default-features = false }
substrate-fixed = { workspace = true, features = ["serde"] }
financial-pallet = { workspace = true }
financial-primitives = { workspace = true }
#Substrate dependencies
frame-support = {workspace = true}
pallet-authorship = { workspace = true }


# Cumulus dependencies
cumulus-pallet-aura-ext = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-pallet-dmp-queue = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-pallet-session-benchmarking = { workspace = true }
pallet-collator-selection = { workspace = true }
parachain-info = { workspace = true }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

# Polkadot dependencies
polkadot-parachain-primitives = { workspace = true }
polkadot-runtime-common = { workspace = true }
polkadot-runtime-constants = { workspace = true }
polkadot-primitives = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
pallet-xcm = { workspace = true }
frame-try-runtime = { workspace = true, optional = true }

equilibrium-curve-amm = { workspace = true }
eq-whitelists = { path = "../../pallets/eq-whitelists", default-features = false }
eq-assets = { path = "../../pallets/eq-assets", default-features = false }
eq-oracle = { path = "../../pallets/eq-oracle", default-features = false }

# pallet-society = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false, optional = true }
aura = { workspace = true }
frame-executive = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-session = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sudo = { workspace = true }
transaction-payment = { workspace = true }
pallet-utility = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
pallet-multisig = { workspace = true }
pallet-proxy = { workspace = true }
pallet-preimage = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-collective = { workspace = true }
pallet-membership = { workspace = true }
pallet-democracy = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
equilibrium-curve-amm-rpc-runtime-api = { workspace = true }

eq-utils = { path = "../../eq-utils", default-features = false }
eq-xcm = { path = "../../eq-xcm", default-features = false }
eq-aggregates = { path = "../../pallets/eq-aggregates", default-features = false }
eq-multisig-sudo = { path = "../../pallets/eq-multisig-sudo", default-features=false }
eq-margin-call = { path = "../../pallets/eq-margin-call", default-features=false }
eq-dex = { path = "../../pallets/eq-dex", default-features = false }
eq-xdot-pool = { path = "../../pallets/eq-xdot-pool", default-features = false }
eq-wrapped-dot = { path = "../../pallets/eq-wrapped-dot", default-features = false }
eq-market-maker = { path = "../../pallets/eq-market-maker", default-features = false }
eq-staking = { path = "../../pallets/eq-staking", default-features = false }
eq-xdot-pool-rpc-runtime-api = { path = "../../pallets/eq-xdot-pool/rpc/runtime-api", default-features = false }
eq-balances-rpc-runtime-api = { path = "../../pallets/eq-balances/rpc/runtime-api", default-features = false }
common-runtime = { path = "../common", default-features = false }
eq-bailsman = { path = "../../pallets/eq-bailsman", default-features = false }
eq-balances = { path = "../../pallets/eq-balances", default-features = false }
eq-rate = { path = "../../pallets/eq-rate", default-features = false }
eq-treasury = { path = "../../pallets/eq-treasury", default-features = false }
eq-vesting = { path = "../../pallets/eq-vesting", default-features = false }
eq-claim = { path = "../../pallets/eq-claim", default-features = false }
eq-distribution = { path = "../../pallets/eq-distribution", default-features = false }
eq-session-manager = { path = "../../pallets/eq-session-manager", default-features = false }
eq-subaccounts = { path = "../../pallets/eq-subaccounts", default-features = false }
eq-lockdrop = { path = "../../pallets/eq-lockdrop", default-features = false }
chainbridge = { path = "../../pallets/chainbridge", default-features = false }
eq-bridge = { path = "../../pallets/eq-bridge", default-features = false }
eq-lending = { path = "../../pallets/eq-lending", default-features = false }
eq-migration = { path = "../../pallets/eq-migration", default-features = false }
eq-primitives = { path = "../../eq-primitives", default-features = false }

[build-dependencies.substrate-wasm-builder]
git = "https://github.com/paritytech/polkadot-sdk"
branch = "release-polkadot-v1.1.0"

[dev-dependencies]
hex-literal = "0.3.1"

[features]
default = ["std"]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime",
  "eq-session-manager/try-runtime",
  "eq-assets/try-runtime",
  "eq-oracle/try-runtime",
  "eq-distribution/try-runtime",
  "eq-treasury/try-runtime",
  "eq-balances/try-runtime",
  "eq-bailsman/try-runtime",
  "eq-whitelists/try-runtime",
  "eq-rate/try-runtime",
  "eq-vesting/try-runtime",
  "eq-claim/try-runtime",
  "eq-aggregates/try-runtime",
  "eq-subaccounts/try-runtime",
  "chainbridge/try-runtime",
  "eq-bridge/try-runtime",
  "eq-multisig-sudo/try-runtime",
  "eq-margin-call/try-runtime",
  "eq-dex/try-runtime",
  "eq-lending/try-runtime",
  "eq-lockdrop/try-runtime",
  "eq-market-maker/try-runtime",
  "eq-xdot-pool/try-runtime",
  "eq-migration/try-runtime",
  "eq-wrapped-dot/try-runtime",
  "eq-staking/try-runtime"
]
std = [
  "common-runtime/std",
  "log/std",
  "aura/std",
  "chainbridge/std",
  "codec/std",
  "financial-pallet/std",
  "financial-primitives/std",
  "frame-executive/std",
  "frame-support/std",
  "pallet-session/std",
  "serde",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-io/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "sudo/std",
  "pallet-timestamp/std",
  "transaction-payment/std",
  "pallet-utility/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "frame-system-rpc-runtime-api/std",
  "serde_json/std",
  "eq-primitives/std",
  "eq-balances/std",
  "eq-bridge/std",
  "eq-assets/std",
  "eq-whitelists/std",
  "eq-bailsman/std",
  "eq-oracle/std",
  "eq-rate/std",
  "eq-session-manager/std",
  "eq-treasury/std",
  "eq-vesting/std",
  "eq-claim/std",
  "eq-aggregates/std",
  "eq-subaccounts/std",
  "sp-arithmetic/std",
  "frame-benchmarking/std",
  "eq-utils/std",
  "eq-distribution/std",
  "eq-multisig-sudo/std",
  "eq-margin-call/std",
  "eq-lending/std",
  "eq-lockdrop/std",
  "equilibrium-curve-amm/std",
  "equilibrium-curve-amm-rpc-runtime-api/std",
  "eq-dex/std",
  "eq-migration/std",
  "pallet-multisig/std",
  "pallet-proxy/std",
  "pallet-preimage/std",
  "pallet-scheduler/std",
  "pallet-collective/std",
  "pallet-membership/std",
  "pallet-democracy/std",
  "cumulus-pallet-aura-ext/std",
  "cumulus-pallet-parachain-system/std",
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "cumulus-pallet-dmp-queue/std",
  "cumulus-pallet-xcmp-queue/std",
  "cumulus-pallet-session-benchmarking/std",
  "pallet-collator-selection/std",
  "parachain-info/std",
  "polkadot-parachain-primitives/std",
  "polkadot-runtime-common/std",
  "polkadot-runtime-constants/std",
  "xcm/std",
  "xcm-builder/std",
  "xcm-executor/std",
  "pallet-xcm/std",
  "eq-xcm/std",
  "eq-xdot-pool/std",
  "eq-xdot-pool-rpc-runtime-api/std",
  "eq-wrapped-dot/std",
  "eq-market-maker/std",
  "eq-staking/std",
  "eq-balances-rpc-runtime-api/std"
]
runtime-benchmarks = [
  # "hex-literal",
  "frame-benchmarking",
  "frame-system/runtime-benchmarks",
  "frame-system-benchmarking",
  "frame-support/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "chainbridge/runtime-benchmarks",
  "eq-claim/runtime-benchmarks",
  "eq-vesting/runtime-benchmarks",
  "eq-balances/runtime-benchmarks",
  "eq-bailsman/runtime-benchmarks",
  "eq-subaccounts/runtime-benchmarks",
  "eq-distribution/runtime-benchmarks",
  "eq-oracle/runtime-benchmarks",
  "eq-whitelists/runtime-benchmarks",
  "eq-treasury/runtime-benchmarks",
  "eq-session-manager/runtime-benchmarks", # "eq-session-manager-benchmarking",
  "eq-bridge/runtime-benchmarks",
  "eq-rate/runtime-benchmarks",
  "eq-dex/runtime-benchmarks",
  "eq-lockdrop/runtime-benchmarks",
  "eq-assets/runtime-benchmarks",
  "eq-margin-call/runtime-benchmarks",
  "eq-multisig-sudo/runtime-benchmarks",
  "pallet-xcm/runtime-benchmarks",
  "xcm-builder/runtime-benchmarks",
  "cumulus-pallet-session-benchmarking/runtime-benchmarks",
  # "pallet-society/runtime-benchmarks",
  "pallet-preimage/runtime-benchmarks",
  "pallet-scheduler/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",
  "pallet-membership/runtime-benchmarks",
  "pallet-democracy/runtime-benchmarks",
  "equilibrium-curve-amm/runtime-benchmarks",
  "eq-lending/runtime-benchmarks",
  "eq-wrapped-dot/runtime-benchmarks",
  "eq-staking/runtime-benchmarks"
]
production = [
  "common-runtime/production",
  "eq-balances/production",
  "eq-vesting/production",
  "eq-claim/production",
  "eq-rate/production",
  "eq-oracle/production",
  "eq-margin-call/production",
  "eq-subaccounts/production",
  "eq-primitives/production",
  "eq-staking/production"
]
logging = [
  "eq-utils/logging"
]
