[package]
name = "eq-xdot-pool-rpc-runtime-api"
version = "0.1.0"
authors = ["equilibrium"]
edition = "2018"

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}
sp-api = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
eq-xdot-pool = { version = "0.1.0", default-features = false, path = "../..", package="eq-xdot-pool" }

[features]
default = ["std"]
std = [
    "sp-std/std",
    "sp-api/std",
    "codec/std",
    "sp-runtime/std",
    "eq-xdot-pool/std",
]
