
//! Autogenerated weights for `eq_whitelists`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-01-09, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `muctep-osx-m1.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/eq-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_whitelists
// --extrinsic=*
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/equilibrium/src/weights/pallet_whitelists.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight}};
use sp_std::marker::PhantomData;

/// Weight functions for `eq_whitelists`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_whitelists::WeightInfo for WeightInfo<T> {
	// Storage: Whitelists WhiteList (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	fn add_to_whitelist() -> Weight {
		Weight::from_parts(27_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Whitelists WhiteList (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: Oracle PricePoints (r:18 w:18)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	fn remove_from_whitelist() -> Weight {
		Weight::from_parts(78_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(21 as u64))
			.saturating_add(T::DbWeight::get().writes(21 as u64))
	}
}
