
//! Autogenerated weights for `eq_subaccounts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-01-09, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `muctep-osx-m1.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/eq-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// eq_subaccounts
// --extrinsic=*
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/equilibrium/src/weights/pallet_subaccounts.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight}};
use sp_std::marker::PhantomData;

/// Weight functions for `eq_subaccounts`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> eq_subaccounts::WeightInfo for WeightInfo<T> {
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:1)
	// Storage: Whitelists WhiteList (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: EqAggregates AccountUserGroups (r:6 w:2)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:1)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: Oracle PricePoints (r:1 w:0)
	// Storage: Bailsman BailsmenCount (r:1 w:1)
	// Storage: Bailsman DistributionQueue (r:1 w:0)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	// Storage: Bailsman LastDistribution (r:0 w:1)
	fn transfer_to_bailsman_register() -> Weight {
		Weight::from_parts(135_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(22 as u64))
			.saturating_add(T::DbWeight::get().writes(11 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:1)
	// Storage: Whitelists WhiteList (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: EqAggregates AccountUserGroups (r:6 w:2)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:1)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	fn transfer_to_borrower_register() -> Weight {
		Weight::from_parts(109_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(19 as u64))
			.saturating_add(T::DbWeight::get().writes(9 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:1)
	// Storage: Whitelists WhiteList (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:3 w:2)
	// Storage: EqAggregates AccountUserGroups (r:6 w:2)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:1)
	// Storage: Oracle PricePoints (r:2 w:0)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: EqLending OnlyBailsmanTill (r:1 w:0)
	// Storage: EqLending LendersAggregates (r:1 w:0)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:0)
	// Storage: EqMarginCall MaintenanceTimers (r:1 w:0)
	// Storage: Bailsman BailsmenCount (r:1 w:1)
	// Storage: Bailsman DistributionQueue (r:1 w:0)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	// Storage: Bailsman LastDistribution (r:0 w:1)
	/// The range of component `r` is `[0, 50]`.
	fn transfer_to_bailsman_and_redistribute(r: u32, ) -> Weight {
		Weight::from_parts(350_820_000 as u64, 0)
			// Standard Error: 64_000
			.saturating_add(Weight::from_parts(1_475_000 as u64, 0).saturating_mul(r as u64))
			.saturating_add(T::DbWeight::get().reads(43 as u64))
			.saturating_add(T::DbWeight::get().writes(11 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:1)
	// Storage: Whitelists WhiteList (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:3 w:2)
	// Storage: EqAggregates AccountUserGroups (r:6 w:2)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:1)
	// Storage: Oracle PricePoints (r:2 w:0)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: EqLending OnlyBailsmanTill (r:1 w:0)
	// Storage: EqLending LendersAggregates (r:1 w:0)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:0)
	// Storage: EqMarginCall MaintenanceTimers (r:1 w:0)
	// Storage: Bailsman BailsmenCount (r:1 w:1)
	// Storage: Bailsman DistributionQueue (r:1 w:0)
	// Storage: EqRate LastFeeUpdate (r:0 w:1)
	// Storage: Bailsman LastDistribution (r:0 w:1)
	fn transfer_to_subaccount() -> Weight {
		Weight::from_parts(226_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(28 as u64))
			.saturating_add(T::DbWeight::get().writes(11 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:0)
	// Storage: EqAggregates AccountUserGroups (r:6 w:1)
	// Storage: Bailsman LastDistribution (r:1 w:1)
	// Storage: Bailsman DistributionQueue (r:1 w:0)
	// Storage: Oracle PricePoints (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:3 w:2)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:0)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: EqLending OnlyBailsmanTill (r:1 w:0)
	// Storage: EqLending LendersAggregates (r:1 w:0)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:0)
	// Storage: EqMarginCall MaintenanceTimers (r:1 w:0)
	// Storage: Bailsman BailsmenCount (r:1 w:1)
	fn transfer_from_subaccount() -> Weight {
		Weight::from_parts(192_000_000 as u64, 0)
			.saturating_add(T::DbWeight::get().reads(26 as u64))
			.saturating_add(T::DbWeight::get().writes(7 as u64))
	}
	// Storage: EqBalances IsTransfersEnabled (r:1 w:0)
	// Storage: Subaccounts Subaccount (r:1 w:0)
	// Storage: EqAggregates AccountUserGroups (r:6 w:1)
	// Storage: Bailsman LastDistribution (r:1 w:1)
	// Storage: Bailsman DistributionQueue (r:1 w:0)
	// Storage: Oracle PricePoints (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:3 w:2)
	// Storage: EqAssets Assets (r:1 w:0)
	// Storage: EqBalances TempMigration (r:2 w:0)
	// Storage: Subaccounts OwnerAccount (r:1 w:0)
	// Storage: EqAggregates TotalUserGroups (r:2 w:2)
	// Storage: EqLending OnlyBailsmanTill (r:1 w:0)
	// Storage: EqLending LendersAggregates (r:1 w:0)
	// Storage: EqDex AssetWeightByAccountId (r:1 w:0)
	// Storage: EqMarginCall MaintenanceTimers (r:1 w:0)
	// Storage: Bailsman BailsmenCount (r:1 w:1)
	/// The range of component `r` is `[0, 50]`.
	fn transfer_from_subaccount_redistribute(r: u32, ) -> Weight {
		Weight::from_parts(1_448_188_000 as u64, 0)
			// Standard Error: 578_000
			.saturating_add(Weight::from_parts(9_766_000 as u64, 0).saturating_mul(r as u64))
			.saturating_add(T::DbWeight::get().reads(77 as u64))
			.saturating_add(T::DbWeight::get().writes(38 as u64))
	}
}
