[package]
name = "eq-xdot-pool"
version = "0.1.0"
authors = ["equilibrium"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.123", optional = true }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.1.0" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.1.0" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.1.0" }
eq-primitives = { path = "../../eq-primitives", default-features = false }
eq-rate = { path = "../eq-rate", package = "eq-rate", default-features = false }
eq-utils = { path = "../../eq-utils", default-features = false }
substrate-fixed = { workspace = true, features = ["serde"] }
eq-assets = { path = "../eq-assets", default-features = false }

[dev-dependencies.eq-oracle]
package = "eq-oracle"
path = "../eq-oracle"
version = "0.1.0"

[dev-dependencies.eq-aggregates]
package = "eq-aggregates"
path = "../eq-aggregates"
version = "0.1.0"

[dev-dependencies.eq-session-manager]
package = "eq-session-manager"
path = "../eq-session-manager"
version = "0.1.0"

[dev-dependencies.pallet-session]
git = "https://github.com/paritytech/polkadot-sdk"
branch = "release-polkadot-v1.1.0"
package = "pallet-session"

[dev-dependencies.pallet-timestamp]
git = "https://github.com/paritytech/polkadot-sdk"
branch = "release-polkadot-v1.1.0"

[dev-dependencies.eq-balances]
package = "eq-balances"
path = "../eq-balances"
version = "0.1.0"

[dev-dependencies.authorship]
default-features = false
git = "https://github.com/paritytech/polkadot-sdk"
branch = "release-polkadot-v1.1.0"
package = "pallet-authorship"

[dev-dependencies.financial-pallet]
default-features = false
git = "https://github.com/equilibrium-eosdt/equilibrium-financial-pallet"
branch = "release-polkadot-v1.1.0"
package = "financial-pallet"
version = "0.1.1"

[dev-dependencies.financial-primitives]
default-features = false
git = "https://github.com/equilibrium-eosdt/equilibrium-financial-pallet"
branch = "release-polkadot-v1.1.0"
package = "financial-primitives"
version = "0.1.0"

[dev-dependencies.test-utils]
default-features = false
package = "test-utils"
path = "../../test-utils"
version = "0.1.0"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"eq-primitives/std",
	"eq-utils/std",
	"eq-rate/std",
	"substrate-fixed/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
]
try-runtime = [
  "frame-support/try-runtime",
]
