[package]
authors = ["equilibrium"]
edition = "2018"
name = "gens-node-runtime"
version = "3.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-arithmetic = {workspace = true}
sp-runtime = { workspace = true }
sp-std = { workspace = true }
frame-benchmarking={workspace = true, optional = true}
frame-system = {workspace = true}
sp-core = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-session = { workspace = true }
equilibrium-curve-amm = { workspace = true }
hex-literal = { version = "0.3.1", optional = true }
serde = {version = "1.0.123", features = ["derive"], optional = true}
serde_json = {git = "https://github.com/nikvolf/json", default-features = false, features = ["alloc"]}
static_assertions = "1.1.0"
smallvec = "1.6.1"
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }

# Substrate dependencies
frame-support = {workspace = true}
pallet-authorship = { workspace = true }
aura = { workspace = true }
frame-executive = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-session = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sudo = { workspace = true }
transaction-payment = { workspace = true }
pallet-utility = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
financial-pallet = { workspace = true }
financial-primitives = { workspace = true }
sp-io = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }

# Cumulus dependencies
cumulus-pallet-aura-ext = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-primitives-aura = { workspace = true }
cumulus-pallet-dmp-queue = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-pallet-session-benchmarking = { workspace = true }
pallet-collator-selection = { workspace = true }
parachain-info = { workspace = true }

# Polkadot dependencies
polkadot-parachain-primitives = { workspace = true}
polkadot-runtime-common = { workspace = true}
polkadot-runtime-constants = { workspace = true}
polkadot-primitives = { workspace = true}
xcm = { workspace = true}
xcm-builder = { workspace = true}
xcm-executor = { workspace = true}
pallet-xcm = { workspace = true}
frame-try-runtime = { workspace = true, optional = true }

substrate-fixed = { workspace = true, features = ["serde"] }
equilibrium-curve-amm-rpc-runtime-api = { workspace = true }

eq-primitives = { path = "../../eq-primitives", default-features = false }
common-runtime = { path = "../common", default-features = false }
eq-balances = { path = "../../pallets/eq-balances", default-features = false }
eq-rate = { path = "../../pallets/eq-rate", default-features = false }
eq-treasury = { path = "../../pallets/eq-treasury", default-features = false }
eq-vesting = { path = "../../pallets/eq-vesting", default-features = false }
eq-distribution = { path = "../../pallets/eq-distribution", default-features = false }
eq-session-manager = { path = "../../pallets/eq-session-manager", default-features = false }
eq-subaccounts = { path = "../../pallets/eq-subaccounts", default-features = false }
chainbridge = { path = "../../pallets/chainbridge", default-features = false }
eq-bridge = { path = "../../pallets/eq-bridge", default-features = false }
eq-lending = { path = "../../pallets/eq-lending", default-features = false }
eq-whitelists = { path = "../../pallets/eq-whitelists", default-features = false }
eq-assets = { path = "../../pallets/eq-assets", default-features = false }
eq-oracle = { path = "../../pallets/eq-oracle", default-features = false }
eq-utils = { path = "../../eq-utils", default-features = false }
eq-xcm = { path = "../../eq-xcm", default-features = false, features = ["kusama"] }
eq-aggregates = { path = "../../pallets/eq-aggregates", default-features = false }
eq-multisig-sudo = { path = "../../pallets/eq-multisig-sudo", default-features=false }
eq-xdot-pool-rpc-runtime-api = { path = "../../pallets/eq-xdot-pool/rpc/runtime-api", default-features = false }
eq-balances-rpc-runtime-api = { path = "../../pallets/eq-balances/rpc/runtime-api", default-features = false }
eq-migration = { path = "../../pallets/eq-migration", default-features = false }
eq-bailsman = { path = "../../pallets/eq-bailsman", default-features = false }
eq-margin-call = { path = "../../pallets/eq-margin-call", default-features=false }
eq-dex = { path = "../../pallets/eq-dex", default-features = false }
gens-binary-opt = { path = "../../pallets/gens-binary-opt", default-features = false }

[build-dependencies.substrate-wasm-builder]
git = "https://github.com/paritytech/polkadot-sdk"
branch = "release-polkadot-v1.1.0"
package = "substrate-wasm-builder"

[features]

default = ["std"]

try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
]

std = [
  "common-runtime/std",
  "log/std",
  "aura/std",
  "chainbridge/std",
  "codec/std",
  "frame-executive/std",
  "frame-support/std",
  "pallet-session/std",
  "financial-pallet/std",
  "financial-primitives/std",
  "serde",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-io/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "sudo/std",
  "pallet-timestamp/std",
  "transaction-payment/std",
  "pallet-utility/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "frame-system-rpc-runtime-api/std",
  "serde_json/std",
  "eq-primitives/std",
  "eq-balances/std",
  "eq-bridge/std",
  "eq-assets/std",
  "eq-rate/std",
  "eq-session-manager/std",
  "eq-treasury/std",
  "eq-vesting/std",
  "eq-aggregates/std",
  "eq-subaccounts/std",
  "sp-arithmetic/std",
  "frame-benchmarking/std",
  "eq-utils/std",
  "eq-distribution/std",
  "eq-multisig-sudo/std",
  "eq-lending/std",
  "cumulus-pallet-aura-ext/std",
  "cumulus-pallet-parachain-system/std",
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "cumulus-pallet-dmp-queue/std",
  "cumulus-pallet-xcmp-queue/std",
  "cumulus-pallet-session-benchmarking/std",
  "pallet-collator-selection/std",
  "parachain-info/std",
  "polkadot-parachain-primitives/std",
  "polkadot-runtime-common/std",
  "polkadot-runtime-constants/std",
  "xcm/std",
  "xcm-builder/std",
  "xcm-executor/std",
  "pallet-xcm/std",
  "eq-xcm/std",
  "equilibrium-curve-amm/std",
  "equilibrium-curve-amm-rpc-runtime-api/std",
  "eq-xdot-pool-rpc-runtime-api/std",
  "eq-whitelists/std",
  "eq-balances-rpc-runtime-api/std",
  "eq-migration/std",
  "eq-bailsman/std",
  "eq-oracle/std",
  "eq-margin-call/std",
  "eq-dex/std",
  "gens-binary-opt/std",
  "cumulus-primitives-aura/std"
]

runtime-benchmarks = [
  "frame-system-benchmarking",
  "hex-literal",
  "frame-benchmarking",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "chainbridge/runtime-benchmarks",
  "eq-vesting/runtime-benchmarks",
  "eq-balances/runtime-benchmarks",
  "eq-subaccounts/runtime-benchmarks",
  "eq-distribution/runtime-benchmarks",
  "eq-treasury/runtime-benchmarks",
  "eq-session-manager/runtime-benchmarks", # "eq-session-manager-benchmarking",
  "eq-bridge/runtime-benchmarks",
  "eq-rate/runtime-benchmarks",
  "eq-assets/runtime-benchmarks",
  "eq-multisig-sudo/runtime-benchmarks",
  "hex-literal",
  "cumulus-pallet-session-benchmarking/runtime-benchmarks",
  "eq-lending/runtime-benchmarks"
]

production = [
  "common-runtime/production",
  "eq-balances/production",
  "eq-vesting/production",
  "eq-rate/production",
  "eq-subaccounts/production",
  "eq-primitives/production",
  "eq-oracle/production",
  "eq-margin-call/production",
]

logging = [
  "eq-utils/logging"
]
experimental = [ "aura/experimental" ]
